# Generated by Django 4.2.1 on 2023-05-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_customuser_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
    ]
